# Taken from https://github.com/kikito/middleclass/blob/master/.travis.yml
os: linux
language: python
sudo: false

env:
  - LUA="lua=5.2"

addons:
  apt:
    packages:
    - libev-dev

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA # --compat=none
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install copas-ev
  - luarocks make rockspec/*-master-1.rockspec

script:
  - luacheck --std max+busted src/
  - busted --verbose --coverage --pattern="-test.lua" --recursive src/
  - cosy-tool  cosy/tool/graphinfo        --graph=cosy/tool/graphinfo-test
  - cosy-tool  cosy/tool/graphinfo-binary --graph=cosy/tool/graphinfo-test

after_success:
  - luacov-coveralls --exclude "test" --exclude "lua_install"

notifications:
  recipients:
    - alban@linard.fr
  email:
    on_success: change
    on_failure: always
